config/routes.rb
Globalpong::Application.routes.draw do
  resources :flying_objects

end

app/models/flying_object.rb
class FlyingObject < ActiveRecord::Base
end

app/models/trajectory.rb
class Trajectory < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flying_objects_controller.rb
class FlyingObjectsController < ApplicationController
  def index
    @flying_objects = FlyingObject.all

    respond_to do |format|
      format.html
      format.json  { render :json => @flying_objects }
    end
  end

  def show
    @flying_object = FlyingObject.find(params[:id])

    respond_to do |format|
      format.html
      format.json  { render :json => @flying_objects }
    end
  end

  # GET /flying_objects/new
  # GET /flying_objects/new.xml
  def new
    @flying_object = FlyingObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flying_object }
    end
  end

  # GET /flying_objects/1/edit
  def edit
    @flying_object = FlyingObject.find(params[:id])
  end

  # POST /flying_objects
  # POST /flying_objects.xml
  def create
    @flying_object = FlyingObject.new(params[:flying_object])

    respond_to do |format|
      if @flying_object.save
        format.html { redirect_to(@flying_object, :notice => 'Flying object was successfully created.') }
        format.xml  { render :xml => @flying_object, :status => :created, :location => @flying_object }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @flying_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flying_objects/1
  # PUT /flying_objects/1.xml
  def update
    @flying_object = FlyingObject.find(params[:id])

    respond_to do |format|
      if @flying_object.update_attributes(params[:flying_object])
        format.html { redirect_to(@flying_object, :notice => 'Flying object was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flying_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flying_objects/1
  # DELETE /flying_objects/1.xml
  def destroy
    @flying_object = FlyingObject.find(params[:id])
    @flying_object.destroy

    respond_to do |format|
      format.html { redirect_to(flying_objects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flying_objects_helper.rb
module FlyingObjectsHelper
end

app/views/flying_objects/_form.html.erb
<%= form_for(@flying_object) do |f| %>
  <% if @flying_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flying_object.errors.count, "error") %> prohibited this flying_object from being saved:</h2>

      <ul>
      <% @flying_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :start_lat %><br />
    <%= f.text_field :start_lat %>
  </div>
  <div class="field">
    <%= f.label :start_lon %><br />
    <%= f.text_field :start_lon %>
  </div>
  <div class="field">
    <%= f.label :aim_lat %><br />
    <%= f.text_field :aim_lat %>
  </div>
  <div class="field">
    <%= f.label :aim_lon %><br />
    <%= f.text_field :aim_lon %>
  </div>
  <div class="field">
    <%= f.label :speed %><br />
    <%= f.text_field :speed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flying_objects/edit.html.erb
<h1>Editing flying_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @flying_object %> |
<%= link_to 'Back', flying_objects_path %>

app/views/flying_objects/index.html.erb
<h1>Listing flying_objects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Created by</th>
    <th>Start lat</th>
    <th>Start lon</th>
    <th>Aim lat</th>
    <th>Aim lon</th>
    <th>Speed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flying_objects.each do |flying_object| %>
  <tr>
    <td><%= flying_object.name %></td>
    <td><%= flying_object.created_by %></td>
    <td><%= flying_object.start_lat %></td>
    <td><%= flying_object.start_lon %></td>
    <td><%= flying_object.aim_lat %></td>
    <td><%= flying_object.aim_lon %></td>
    <td><%= flying_object.speed %></td>
    <td><%= link_to 'Show', flying_object %></td>
    <td><%= link_to 'Edit', edit_flying_object_path(flying_object) %></td>
    <td><%= link_to 'Destroy', flying_object, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flying object', new_flying_object_path %>

app/views/flying_objects/new.html.erb
<h1>New flying_object</h1>

<%= render 'form' %>

<%= link_to 'Back', flying_objects_path %>

app/views/flying_objects/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "default" %>
  <%= stylesheet_link_tag "main", :media => "screen and (min-device-width: 481px)" %>
  <%= stylesheet_link_tag "mobile", :media => "screen and (max-device-width: 480px)" %>
  <%= javascript_include_tag "http://www.google.com/jsapi?key=ABQIAAAA6xOQSzg1vY1kb3Oind4DWxS6wmucxyPyZRD4GEjyZVIp_7_-chSlNeLzwuQqUrNOQ-6zQjKiAhg7uA" %> 
  <%= javascript_include_tag "ajaxlibs", "latlong", "maps" %> 
<% end %>

<div id="data"> 
  <div id="creator"><%= @flying_object.created_by %></div> 
  <div id="startLat"><%= @flying_object.start_lat %></div>
  <div id="startLon"><%= @flying_object.start_lon %></div>
  <div id="aimLat"><%= @flying_object.aim_lat %></div>
  <div id="aimLon"><%= @flying_object.aim_lon %></div>
  <div id="startTime"><%= @flying_object.created_at %></div>
  <div id="speed"><%= @flying_object.speed %></div> 
</div>
<div id="content"> 
  <div id="header"><h1>global pong</h1></div> 
  <div id="map"></div> 
  <div id="badge"> 
   <h2><%= @flying_object.name %></h2>

   <p>This ball was created by <span class="info"><%= @flying_object.created_by %></span> on <span class="info"><%= @flying_object.created_at %></span></p>

   <p>It was launched from (<span class="info"><%= @flying_object.start_lat %></span>,<span class="info"><%= @flying_object.start_lon %></span>) heading towards (<span class="info"><%= @flying_object.aim_lat %></span>,<span class="info"><%= @flying_object.aim_lon %></span>) at <span class="info"><%= @flying_object.speed %></span> km/h</p>

   <p>It is now located at (<span class="info" id="currentLat"></span>,<span class="info" id="currentLon"></span>)</p> 
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || 'Global Pong' %></title>
  <%= csrf_meta_tag %>
  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>